name: activity-recognition-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - flask
  - flask-smorest
  - flask-restful
  - pipreqs
  - psycopg2
  - sentry-sdk[flask]
  - blinker
